# Generated by Django 4.2.9 on 2024-10-05 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='task',
            name='user_story',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='task_manager.userstory'),
            preserve_default=False,
        ),
    ]
