# Generated by Django 4.2.9 on 2024-10-05 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_alter_company_options_alter_task_user_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='sprints', to='task_manager.company'),
            preserve_default=False,
        ),
    ]
