# Generated by Django 4.2.9 on 2024-10-04 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_alter_task_parent_task_alter_task_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status_column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='task_manager.statuscolumn'),
        ),
    ]
