# Generated by Django 4.2.9 on 2024-10-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_task_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ManyToManyField(related_name='users', to='task_manager.company'),
        ),
    ]
