# Generated by Django 4.2.9 on 2024-10-06 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_remove_user_company_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(default='35898367-4782-417d-81dd-fde1f5f94aac', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='task_manager.company'),
            preserve_default=False,
        ),
    ]
