# Generated by Django 4.2.9 on 2024-10-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_task_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscolumn',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
